name: Backend Tests

on:
  pull_request:
    branches:
      - "main"
      - "master"
    types: [opened, synchronize, reopened]
    paths:
      - 'chatbot-core/**'

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: chatbot-core
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        working-directory: chatbot-core
        env:
          PYTHONPATH: ${{github.workspace}}/chatbot-core
        run: |
          pytest tests/unit
      - name: Run integration tests
        working-directory: chatbot-core
        env:
          PYTHONPATH: ${{github.workspace}}/chatbot-core
        run: |
          pytest tests/integration
